"""
This type stub file was generated by pyright.
"""

import argparse

"""Command-line interface to WeasyPrint."""
class PrintInfo(argparse.Action):
    def __call__(*_, **__):
        ...
    


class Parser(argparse.ArgumentParser):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def add_argument(self, *args, _group_name=..., **kwargs) -> None:
        ...
    
    def add_argument_group(self, name, *args, **kwargs) -> _ArgumentGroup:
        ...
    
    @property
    def docstring(self) -> LiteralString:
        ...
    


PARSER = ...
group = ...
group = ...
group = ...
group = ...
def main(argv=..., stdout=..., stdin=..., HTML=...) -> None:
    """The ``weasyprint`` program takes at least two arguments:

    .. code-block:: sh

        weasyprint [options] <input> <output>

    """
    ...

if __name__ == '__main__':
    ...
