"""
This type stub file was generated by pyright.
"""

import codecs
import contextlib
from gzip import GzipFile
from urllib import request

"""Various utility functions and classes for URL management."""
UNICODE_SCHEME_RE = ...
BYTES_SCHEME_RE = ...
FILESYSTEM_ENCODING = ...
if codecs.lookup(FILESYSTEM_ENCODING).name == 'ascii':
    FILESYSTEM_ENCODING = ...
HTTP_HEADERS = ...
class StreamingGzipFile(GzipFile):
    def __init__(self, fileobj) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    def seekable(self) -> Literal[False]:
        ...
    


def iri_to_uri(url) -> str:
    """Turn a Unicode IRI into an ASCII-only URI that conforms to RFC 3986."""
    ...

def path2url(path) -> str:
    """Return file URL of `path`.

    Accepts 'str', 'bytes' or 'Path', returns 'str'.

    """
    ...

def url_is_absolute(url) -> bool:
    """Return whether an URL (bytes or string) is absolute."""
    ...

def get_url_attribute(element, attr_name, base_url, allow_relative=...) -> str | None:
    """Get the URI corresponding to the ``attr_name`` attribute.

    Return ``None`` if:

    * the attribute is empty or missing or,
    * the value is a relative URI but the document has no base URI and
      ``allow_relative`` is ``False``.

    Otherwise return an URI, absolute if possible.

    """
    ...

def get_url_tuple(url, base_url) -> tuple[Literal['internal'], str] | tuple[Literal['external'], Any | str] | None:
    """Get tuple describing internal or external URI."""
    ...

def url_join(base_url, url, allow_relative, context, context_args) -> str | None:
    """Like urllib.urljoin, but warn if base_url is required but missing."""
    ...

def get_link_attribute(element, attr_name, base_url) -> tuple[Literal['url'], tuple[str, str]] | tuple[Literal['url'], tuple[str, Any | str]] | None:
    """Get the URL value of an element attribute.

    Return ``('external', absolute_uri)``, or ``('internal',
    unquoted_fragment_id)``, or ``None``.

    """
    ...

def ensure_url(string) -> str:
    """Get a ``scheme://path`` URL from ``string``.

    If ``string`` looks like an URL, return it unchanged. Otherwise assume a
    filename and convert it to a ``file://`` URL.

    """
    ...

def default_url_fetcher(url, timeout=..., ssl_context=..., http_headers=..., allowed_protocols=...) -> URLFetcherResponse:
    """Fetch an external resource such as an image or stylesheet.

    This function is deprecated, use ``URLFetcher`` instead.

    """
    ...

@contextlib.contextmanager
def select_source(guess=..., filename=..., url=..., file_obj=..., string=..., base_url=..., url_fetcher=..., check_css_mime_type=...) -> Generator[Any | tuple[BufferedReader[_BufferedReaderStream], str | Any, None, None] | tuple[StringIO, Any | str | None, None, None] | tuple[URLFetcherResponse, Any | str, _ParamType | None, str] | tuple[Any, Any | str | None, None, None] | tuple[BytesIO, Any | str | None, None, None], Any, None]:
    """If only one input is given, return it.

    Yield a file object, the base url, the protocol encoding and the protocol mime-type.

    """
    ...

class URLFetchingError(IOError):
    """Some error happened when fetching an URL."""
    ...


class FatalURLFetchingError(BaseException):
    """Some error happened when fetching an URL and must stop the rendering."""
    ...


class URLFetcher(request.OpenerDirector):
    """Fetcher of external resources such as images or stylesheets.

    :param int timeout: The number of seconds before HTTP requests are dropped.
    :param ssl.SSLContext ssl_context: An SSL context used for HTTPS requests.
    :param dict http_headers: Additional HTTP headers used for HTTP requests.
    :type allowed_protocols: :term:`sequence`
    :param allowed_protocols: A set of authorized protocols, :obj:`None` means all.
    :param bool allow_redirects: Whether HTTP redirects must be followed.
    :param bool fail_on_errors: Whether HTTP errors should stop the rendering.

    Another class inheriting from this class, with a ``fetch`` method that has a
    compatible signature, can be given as the ``url_fetcher`` argument to
    :class:`weasyprint.HTML` or :class:`weasyprint.CSS`.

    See :ref:`URL Fetchers` for more information and examples.

    """
    def __init__(self, timeout=..., ssl_context=..., http_headers=..., allowed_protocols=..., allow_redirects=..., fail_on_errors=..., **kwargs) -> None:
        ...
    
    def fetch(self, url, headers=...) -> URLFetcherResponse:
        """Fetch a given URL.

        :returns: A :obj:`URLFetcherResponse` instance.
        :raises: An exception indicating failure, e.g. :obj:`ValueError` on
            syntactically invalid URL. All exceptions are catched internally by
            WeasyPrint, except when they inherit from :obj:`FatalURLFetchingError`.

        """
        ...
    
    def open(self, url, data=..., timeout=...) -> URLFetcherResponse:
        ...
    
    def __call__(self, url) -> URLFetcherResponse:
        ...
    


class URLFetcherResponse:
    """The HTTP response of an URL fetcher.

    :param str url: The URL of the HTTP response.
    :type body: :class:`str`, :class:`bytes` or :term:`file object`
    :param body: The body of the HTTP response.
    :type headers: dict or email.message.EmailMessage
    :param headers: The headers of the HTTP response.
    :param int status: The status of the HTTP response.

    Has the same interface as :class:`urllib.response.addinfourl`.

    If a :term:`file object` is given for the body, it is the caller’s responsibility to
    call ``close()`` on it. The default function used internally to fetch data in
    WeasyPrint tries to close the file object after retreiving; but if this URL fetcher
    is used elsewhere, the file object has to be closed manually.

    """
    def __init__(self, url, body=..., headers=..., status=..., **kwargs) -> None:
        ...
    
    def read(self, *args, **kwargs) -> bytes:
        ...
    
    def close(self) -> None:
        ...
    
    @property
    def path(self) -> str | None:
        ...
    
    @property
    def content_type(self) -> str:
        ...
    
    @property
    def charset(self) -> _ParamType | None:
        ...
    
    def geturl(self) -> Any:
        ...
    
    def info(self) -> EmailMessage:
        ...
    
    @property
    def code(self) -> int:
        ...
    
    def getcode(self) -> int:
        ...
    


@contextlib.contextmanager
def fetch(url_fetcher, url) -> Generator[URLFetcherResponse, Any, None]:
    """Fetch an ``url`` with ```url_fetcher``, fill in optional data, and clean up.

    Fatal errors must raise a ``FatalURLFetchingError`` that stops the rendering. All
    other exceptions are catched and raise an ``URLFetchingError``, that is usually
    catched by the code that fetches the resource and emits a warning.

    """
    ...

