"""init db

Revision ID: 071dd735e07c
Revises: 
Create Date: 2026-04-15 17:22:53.461887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071dd735e07c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_duration_ms', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('count_2xx', sa.Integer(), nullable=False),
    sa.Column('count_3xx', sa.Integer(), nullable=False),
    sa.Column('count_4xx', sa.Integer(), nullable=False),
    sa.Column('count_5xx', sa.Integer(), nullable=False),
    sa.Column('count_get', sa.Integer(), nullable=False),
    sa.Column('count_post', sa.Integer(), nullable=False),
    sa.Column('count_put', sa.Integer(), nullable=False),
    sa.Column('count_delete', sa.Integer(), nullable=False),
    sa.Column('count_patch', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stat_date')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('error_type', sa.String(length=256), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_logs_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_user_id'), ['user_id'], unique=False)

    op.create_table('simulation_inputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pitch', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_inputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_inputs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_inputs_pitch'), ['pitch'], unique=False)

    op.create_table('transcricoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transcricao', sa.Text(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcricoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcricoes_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    op.create_table('atas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('numero_ata', sa.String(), nullable=True),
    sa.Column('orgao', sa.String(), nullable=True),
    sa.Column('sala', sa.String(), nullable=True),
    sa.Column('dia', sa.String(), nullable=True),
    sa.Column('mes', sa.String(), nullable=True),
    sa.Column('n_ano', sa.String(), nullable=True),
    sa.Column('hora_inicio', sa.String(), nullable=True),
    sa.Column('minutos_inicio', sa.String(), nullable=True),
    sa.Column('hora_fim', sa.String(), nullable=True),
    sa.Column('minutos_fim', sa.String(), nullable=True),
    sa.Column('participantes', sa.Text(), nullable=True),
    sa.Column('ausentes', sa.Text(), nullable=True),
    sa.Column('condutor', sa.String(), nullable=True),
    sa.Column('secretario', sa.String(), nullable=True),
    sa.Column('tema', sa.String(), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('assuntos_discutidos', sa.Text(), nullable=True),
    sa.Column('deliberacoes', sa.Text(), nullable=True),
    sa.Column('info_adicional', sa.Text(), nullable=True),
    sa.Column('transcricao_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('COMPLETE', 'DOING', 'INTERRUPTED', 'STALE', name='atastatus'), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transcricao_id'], ['transcricoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcricao_id')
    )
    with op.batch_alter_table('atas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atas_numero_ata'), ['numero_ata'], unique=False)

    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_input_id', sa.String(length=36), nullable=False),
    sa.Column('scene_organization', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.Text(), nullable=True),
    sa.Column('case_presentation', sa.Text(), nullable=True),
    sa.Column('students_briefing', sa.Text(), nullable=True),
    sa.Column('debriefing', sa.Text(), nullable=True),
    sa.Column('appendix', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('uses_simulator', sa.Integer(), nullable=True),
    sa.Column('students_quantity', sa.Integer(), nullable=True),
    sa.Column('actors_quantity', sa.Integer(), nullable=True),
    sa.Column('students_role', sa.String(), nullable=True),
    sa.Column('actors_role', sa.String(), nullable=True),
    sa.Column('simulator_role', sa.String(), nullable=True),
    sa.Column('simulator_parameters', sa.Text(), nullable=True),
    sa.Column('simulator_evolution_parameters', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETE', 'DOING', 'INTERRUPTED', 'STALE', name='simulationstatus'), nullable=False),
    sa.Column('pdf_status', sa.Enum('IDLE', 'GENERATING', 'READY', 'ERROR', name='pdfstatus'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_input_id'], ['simulation_inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulations_id'), ['id'], unique=False)

    op.create_table('actors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personal_data', sa.Text(), nullable=True),
    sa.Column('current_story', sa.Text(), nullable=True),
    sa.Column('previous_story', sa.Text(), nullable=True),
    sa.Column('clothing', sa.String(), nullable=True),
    sa.Column('behavior_profile', sa.Text(), nullable=True),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actors_id'), ['id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_id'), ['id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_id'), ['id'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_plan_a', sa.Text(), nullable=True),
    sa.Column('actor_sim_directions', sa.Text(), nullable=True),
    sa.Column('actor_plan_b', sa.Text(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_id'))

    op.drop_table('materials')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actors_id'))

    op.drop_table('actors')
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_id'))

    op.drop_table('simulations')
    with op.batch_alter_table('atas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atas_numero_ata'))
        batch_op.drop_index(batch_op.f('ix_atas_id'))

    op.drop_table('atas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('transcricoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcricoes_id'))

    op.drop_table('transcricoes')
    with op.batch_alter_table('simulation_inputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_inputs_pitch'))
        batch_op.drop_index(batch_op.f('ix_simulation_inputs_id'))

    op.drop_table('simulation_inputs')
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_request_logs_path'))
        batch_op.drop_index(batch_op.f('ix_request_logs_method'))
        batch_op.drop_index(batch_op.f('ix_request_logs_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_error_type'))

    op.drop_table('request_logs')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
