"""changed scene field names

Revision ID: 29120e0fbf44
Revises: 
Create Date: 2026-03-12 10:44:45.180634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29120e0fbf44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_inputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pitch', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_inputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_inputs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_inputs_pitch'), ['pitch'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    op.create_table('simulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_input_id', sa.String(length=36), nullable=False),
    sa.Column('scene_organization', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.Text(), nullable=True),
    sa.Column('case_presentation', sa.Text(), nullable=True),
    sa.Column('students_briefing', sa.Text(), nullable=True),
    sa.Column('debriefing', sa.Text(), nullable=True),
    sa.Column('appendix', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('uses_simulator', sa.Integer(), nullable=True),
    sa.Column('students_quantity', sa.Integer(), nullable=True),
    sa.Column('actors_quantity', sa.Integer(), nullable=True),
    sa.Column('students_role', sa.String(), nullable=True),
    sa.Column('actors_role', sa.String(), nullable=True),
    sa.Column('simulator_role', sa.String(), nullable=True),
    sa.Column('simulator_parameters', sa.Text(), nullable=True),
    sa.Column('simulator_evolution_parameters', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETE', 'DOING', 'INTERRUPTED', 'STALE', name='simulationstatus'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_input_id'], ['simulation_inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulations_id'), ['id'], unique=False)

    op.create_table('actors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('personal_data', sa.Text(), nullable=True),
    sa.Column('current_story', sa.Text(), nullable=True),
    sa.Column('previous_story', sa.Text(), nullable=True),
    sa.Column('clothing', sa.String(), nullable=True),
    sa.Column('behavior_profile', sa.Text(), nullable=True),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actors_id'), ['id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_id'), ['id'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_plan_a', sa.Text(), nullable=True),
    sa.Column('actor_sim_directions', sa.Text(), nullable=True),
    sa.Column('student_plan_b', sa.Text(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_id'))

    op.drop_table('materials')
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actors_id'))

    op.drop_table('actors')
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_id'))

    op.drop_table('simulations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('simulation_inputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_inputs_pitch'))
        batch_op.drop_index(batch_op.f('ix_simulation_inputs_id'))

    op.drop_table('simulation_inputs')
    # ### end Alembic commands ###
