"""add status and error to simulations

Revision ID: 4f2f5d8dbc5e
Revises: 7f089614b89b
Create Date: 2026-02-24 10:13:54.248859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2f5d8dbc5e'
down_revision: Union[str, Sequence[str], None] = '7f089614b89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('COMPLETE', 'DOING', 'INTERRUPTED', 'STALE', name='simulationstatus'), nullable=False, server_default='COMPLETE'))
        batch_op.add_column(sa.Column('error', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('error')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
