"""add_request_logs_table

Revision ID: 6a96ad69f3e7
Revises: 6da6c0eb2b85
Create Date: 2026-04-02 11:12:09.360785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a96ad69f3e7'
down_revision: Union[str, Sequence[str], None] = '6da6c0eb2b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('error_type', sa.String(length=256), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_logs_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_request_logs_path'))
        batch_op.drop_index(batch_op.f('ix_request_logs_method'))
        batch_op.drop_index(batch_op.f('ix_request_logs_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_error_type'))

    op.drop_table('request_logs')
    # ### end Alembic commands ###
