"""new field

Revision ID: b4133ef41eb9
Revises: f0e763866b02
Create Date: 2026-03-12 13:53:33.018489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4133ef41eb9'
down_revision: Union[str, Sequence[str], None] = 'f0e763866b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_status', sa.Enum('IDLE', 'GENERATING', 'READY', 'ERROR', name='pdfstatus'), server_default='READY', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('pdf_status')

    # ### end Alembic commands ###
