"""ata

Revision ID: fd68c8b9e955
Revises: 197baf5f90c0
Create Date: 2026-03-24 09:56:15.327405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd68c8b9e955'
down_revision: Union[str, Sequence[str], None] = '197baf5f90c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcricoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transcricao', sa.Text(), nullable=False),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcricoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcricoes_id'), ['id'], unique=False)

    op.create_table('atas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('numero_ata', sa.String(), nullable=True),
    sa.Column('orgao', sa.String(), nullable=True),
    sa.Column('sala', sa.String(), nullable=True),
    sa.Column('dia', sa.String(), nullable=True),
    sa.Column('mes', sa.String(), nullable=True),
    sa.Column('n_ano', sa.String(), nullable=True),
    sa.Column('hora_inicio', sa.String(), nullable=True),
    sa.Column('minutos_inicio', sa.String(), nullable=True),
    sa.Column('hora_fim', sa.String(), nullable=True),
    sa.Column('minutos_fim', sa.String(), nullable=True),
    sa.Column('participantes', sa.Text(), nullable=True),
    sa.Column('ausentes', sa.Text(), nullable=True),
    sa.Column('condutor', sa.String(), nullable=True),
    sa.Column('secretario', sa.String(), nullable=True),
    sa.Column('tema', sa.String(), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('assuntos_discutidos', sa.Text(), nullable=True),
    sa.Column('deliberacoes', sa.Text(), nullable=True),
    sa.Column('transcricao_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transcricao_id'], ['transcricoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcricao_id')
    )
    with op.batch_alter_table('atas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atas_numero_ata'), ['numero_ata'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atas_numero_ata'))
        batch_op.drop_index(batch_op.f('ix_atas_id'))

    op.drop_table('atas')
    with op.batch_alter_table('transcricoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcricoes_id'))

    op.drop_table('transcricoes')
    # ### end Alembic commands ###
