"""
This type stub file was generated by pyright.
"""

"""CSS functions parsers."""
class Function:
    """CSS function."""
    def __init__(self, token) -> None:
        """Create Function from function token."""
        ...
    
    def split_space(self) -> list[Any] | None:
        """Split arguments on spaces."""
        ...
    
    def split_comma(self, single_tokens=..., trailing=...) -> list[Any | None] | list[list[Any]] | list[Any] | None:
        """Split arguments on commas.

        Spaces in parentheses and after commas are removed.

        If ``single_tokens`` is ``True``, check that only a single token is between
        commas and flatten returned list.

        If ``trailing`` is ``True``, allow a bare comma at the end.

        """
        ...
    


def check_attr(token, allowed_type=...) -> tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | None:
    ...

def check_counter(token, allowed_type=...) -> tuple[LiteralString, tuple[Any, ...]] | None:
    ...

def check_content(token) -> tuple[Literal['content()'], Literal['text']] | tuple[Literal['content()'], Literal['text', 'before', 'after', 'first-letter', 'marker']] | None:
    ...

def check_string_or_element(string_or_element, token) -> tuple[str, tuple[Any, str]] | None:
    ...

def check_var(token) -> bool | None:
    ...

def check_math(token) -> bool | None:
    ...

