"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod

"""CSS tokens parsers."""
ZERO_PERCENT = ...
FIFTY_PERCENT = ...
HUNDRED_PERCENT = ...
BACKGROUND_POSITION_PERCENTAGES = ...
DIRECTION_KEYWORDS = ...
E = ...
PI = ...
PLUS_INFINITY = ...
MINUS_INFINITY = ...
NAN = ...
class InvalidValues(ValueError):
    """Invalid or unsupported values for a known CSS property."""
    ...


class PercentageInMath(ValueError):
    """Percentage in math function without reference length."""
    ...


class FontUnitInMath(ValueError):
    """Font-relative unit in math function without reference style."""
    ...


class Pending(ABC):
    """Abstract class representing property value with pending validation."""
    def __init__(self, tokens, name) -> None:
        ...
    
    @abstractmethod
    def validate(self, tokens, wanted_key):
        """Get validated value for wanted key."""
        ...
    
    def solve(self, tokens, wanted_key):
        """Get validated value or raise error."""
        ...
    


def parse_color_hint(tokens) -> Dimension | None:
    ...

def parse_color_stop(tokens) -> tuple[tinycss2.color4.Color | tinycss2.color5.Color | Any | Literal['currentcolor'] | None, None] | tuple[tinycss2.color4.Color | tinycss2.color5.Color | Any, None] | tuple[tinycss2.color4.Color | tinycss2.color5.Color | Any | Literal['currentcolor'], Any | Dimension]:
    ...

def parse_color_stops_and_hints(color_stops_hints) -> tuple[list[tuple[tinycss2.color4.Color | tinycss2.color5.Color | Any | Literal['currentcolor'] | None, None] | tuple[tinycss2.color4.Color | tinycss2.color5.Color | Any, None] | tuple[tinycss2.color4.Color | tinycss2.color5.Color | Any | Literal['currentcolor'], Any | Dimension]], list[Any]]:
    ...

def parse_linear_gradient_parameters(arguments) -> tuple[tuple[str, Any | int], Any] | tuple[tuple[str, int] | tuple[str, float] | tuple[str, str], Any] | tuple[tuple[str, float], Any]:
    ...

def parse_2d_position(tokens) -> tuple[Any | Dimension, Any | Dimension] | tuple[Any | Dimension, Dimension] | tuple[Dimension, Any | Dimension] | tuple[Dimension, Dimension] | None:
    """Common syntax of background-position and transform-origin."""
    ...

def parse_position(tokens) -> tuple[Literal['left'], Any | Dimension, Literal['top'], Any | Dimension] | tuple[Literal['left', 'right'], Any | Dimension, Literal['top', 'bottom'], Any | Dimension] | tuple[Literal['left'], Dimension, Literal['top', 'bottom'], Any | Dimension] | tuple[Literal['left', 'right'], Any | Dimension, Literal['top'], Dimension] | tuple[Literal['left', 'right'], Any | Dimension, Literal['top', 'bottom'], Dimension] | tuple[Literal['left', 'right'], Dimension, Literal['top', 'bottom'], Any | Dimension] | None:
    """Parse background-position and object-position.

    See https://drafts.csswg.org/css-backgrounds-3/#the-background-position
    https://drafts.csswg.org/css-images-3/#propdef-object-position

    """
    ...

def parse_radial_gradient_parameters(arguments) -> tuple[Literal['circle', 'ellipse'], tuple[Literal['keyword'], Literal['closest-corner', 'farthest-corner', 'closest-side', 'farthest-side']] | tuple[Literal['keyword'], Literal['farthest-corner']] | tuple[Literal['explicit'], tuple[Any | Dimension, Any | Dimension]] | tuple[Literal['explicit'], tuple[Any | Dimension | None, Any | Dimension | None]], tuple[Literal['left'], Any | Dimension, Literal['top'], Any | Dimension] | tuple[Literal['left'], Dimension, Literal['top'], Dimension] | tuple[Literal['left', 'right'], Any | Dimension, Literal['top', 'bottom'], Any | Dimension] | tuple[Literal['left'], Dimension, Literal['top', 'bottom'], Any | Dimension] | tuple[Literal['left', 'right'], Any | Dimension, Literal['top'], Dimension] | tuple[Literal['left', 'right'], Any | Dimension, Literal['top', 'bottom'], Dimension] | tuple[Literal['left', 'right'], Dimension, Literal['top', 'bottom'], Any | Dimension], Any] | None:
    ...

def split_on_comma(tokens) -> tuple[Any, ...]:
    """Split a list of tokens on commas, ie ``LiteralToken(',')``.

    Only "top-level" comma tokens are splitting points, not commas inside a
    function or blocks.

    """
    ...

def remove_whitespace(tokens) -> tuple[Any, ...]:
    """Remove any top-level whitespace and comments in a token list."""
    ...

def get_keyword(token) -> None:
    """If ``token`` is a keyword, return its lowercase name.

    Otherwise return ``None``.

    """
    ...

def get_custom_ident(token) -> None:
    """If ``token`` is a keyword, return its name.

    Otherwise return ``None``.

    """
    ...

def get_single_keyword(tokens) -> None:
    """If ``values`` is a 1-element list of keywords, return its name.

    Otherwise return ``None``.

    """
    ...

def get_number(token, negative=..., integer=...) -> Dimension | None:
    """Parse a <number> token."""
    ...

def get_string(token) -> tuple[Literal['string'], Any] | tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | tuple[LiteralString, tuple[Any, ...]] | tuple[Literal['content()'], Literal['text']] | tuple[Literal['content()'], Literal['text', 'before', 'after', 'first-letter', 'marker']] | tuple[LiteralString, tuple[Any, str]] | None:
    """Parse a <string> token."""
    ...

def get_percentage(token, negative=...) -> Dimension | None:
    """Parse a <percentage> token."""
    ...

def get_length(token, negative=..., percentage=...) -> Dimension | None:
    """Parse a <length> token."""
    ...

def get_angle(token) -> Literal[0] | None:
    """Parse an <angle> token in radians."""
    ...

def get_resolution(token) -> None:
    """Parse a <resolution> token in dppx."""
    ...

def get_image(token, base_url) -> tuple[Literal['url'], Any | str] | tuple[Literal['linear-gradient'], LinearGradient] | tuple[Literal['radial-gradient'], RadialGradient] | None:
    """Parse an <image> token."""
    ...

def get_url(token, base_url) -> tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | tuple[Literal['url'], tuple[Literal['internal'], str] | tuple[Literal['external'], Any | str]] | None:
    """Parse an <url> token."""
    ...

def get_quote(token) -> Literal['open-quote', 'close-quote', 'no-open-quote', 'no-close-quote'] | None:
    """Parse a <quote> token."""
    ...

def get_target(token, base_url) -> tuple[LiteralString, tuple[Any, ...]] | None:
    """Parse a <target> token."""
    ...

def get_content_list(tokens, base_url) -> list[tuple[Literal['string'], Any] | tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | tuple[LiteralString, tuple[Any, ...]] | tuple[Literal['content()'], Literal['text']] | tuple[Literal['content()'], Literal['text', 'before', 'after', 'first-letter', 'marker']] | tuple[LiteralString, tuple[Any, str]] | tuple[Literal['url'], tuple[Literal['internal'], str] | tuple[Literal['external'], Any | str]] | tuple[Literal['quote'], Literal['open-quote', 'close-quote', 'no-open-quote', 'no-close-quote']] | tuple[Literal['leader()'], tuple[str, Any | str | None]] | None] | None:
    """Parse <content-list> tokens."""
    ...

def get_content_list_token(token, base_url) -> tuple[Literal['string'], Any] | tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | tuple[LiteralString, tuple[Any, ...]] | tuple[Literal['content()'], Literal['text']] | tuple[Literal['content()'], Literal['text', 'before', 'after', 'first-letter', 'marker']] | tuple[LiteralString, tuple[Any, str]] | tuple[Literal['url'], tuple[Literal['internal'], str] | tuple[Literal['external'], Any | str]] | tuple[Literal['quote'], Literal['open-quote', 'close-quote', 'no-open-quote', 'no-close-quote']] | tuple[Literal['leader()'], tuple[str, Any | str | None]] | None:
    """Parse one of the <content-list> tokens."""
    ...

def single_keyword(function) -> _Wrapped[..., Any, ..., Any | None]:
    """Decorator for validators that only accept a single keyword."""
    ...

def single_token(function) -> _Wrapped[..., Any, ..., Any | None]:
    """Decorator for validators that only accept a single token."""
    ...

def comma_separated_list(function) -> _Wrapped[..., Any, ..., tuple[Any, ...] | None]:
    """Decorator for validators that accept a comma separated list."""
    ...

def tokenize(item, function=..., unit=...) -> DimensionToken | PercentageToken | NumberToken | None:
    """Transform a computed value result into a token."""
    ...

