"""
This type stub file was generated by pyright.
"""

"""Draw colors."""
def get_color(style, key):
    """Return color, taking care of possible currentColor value."""
    ...

def darken(color) -> tinycss2.color4.Color | tinycss2.color5.Color | Literal['currentcolor'] | None:
    """Return a darker color."""
    ...

def lighten(color) -> tinycss2.color4.Color | tinycss2.color5.Color | Literal['currentcolor'] | None:
    """Return a lighter color."""
    ...

def styled_color(style, color, side) -> tinycss2.color4.Color | tinycss2.color5.Color | tuple[tinycss2.color4.Color | tinycss2.color5.Color | Any | Literal['currentcolor'] | None, tinycss2.color4.Color | tinycss2.color5.Color | Any | Literal['currentcolor'] | None] | Literal['currentcolor'] | None:
    """Return inset, outset, ridge and groove border colors."""
    ...

