"""
This type stub file was generated by pyright.
"""

"""PDF metadata stream generation."""
NS = ...
class DocumentMetadata:
    """Meta-information belonging to a whole :class:`Document`.

    New attributes may be added in future versions of WeasyPrint.
    """
    def __init__(self, title=..., authors=..., description=..., keywords=..., generator=..., created=..., modified=..., attachments=..., lang=..., custom=..., xmp_metadata=...) -> None:
        ...
    
    def include_in_pdf(self, pdf, variant, version, conformance, compress) -> None:
        """Add PDF stream of metadata.

        Described in ISO-32000-1:2008, 14.3.2.

        """
        ...
    
    def generate_rdf_metadata(self, variant, version, conformance) -> Any:
        """Generate RDF metadata as a bytestring."""
        ...
    


