"""
This type stub file was generated by pyright.
"""

"""PDF/X generation."""
def pdfx(pdf, metadata, document, page_streams, attachments, compress, version, variant) -> None:
    """Set metadata for PDF/X documents."""
    ...

VARIANTS = ...
