"""
This type stub file was generated by pyright.
"""

"""Parse and draw definitions: gradients, patterns, masks, uses…"""
def get_use_tree(svg, node, font_size) -> Node | None:
    ...

def use(svg, node, font_size) -> None:
    """Draw use tags."""
    ...

def draw_gradient_or_pattern(svg, node, name, font_size, opacity, stroke) -> bool | None:
    """Draw given gradient or pattern."""
    ...

def draw_gradient(svg, node, gradient, font_size, opacity, stroke) -> bool:
    """Draw given gradient node."""
    ...

def spread_linear_gradient(spread, positions, colors, x1, y1, x2, y2, bounding_box, matrix) -> tuple[Literal[1], Literal['solid'], None, list[Any], list[tinycss2.color4.Color | tinycss2.color5.Color | Any | str | None]] | tuple[list[int] | list[Any], Any, tuple[Any, Any, Any, Any]]:
    """Repeat linear gradient."""
    ...

def spread_radial_gradient(spread, positions, colors, fx, fy, fr, cx, cy, r, width, height, matrix) -> tuple[list[int | Any] | list[int] | list[Any], Any | list[Any], tuple[Any, Any, Literal[0], Any, Any, Any]] | tuple[list[int | Any] | list[int] | list[Any], Any | list[tinycss2.color4.Color | tinycss2.color5.Color | Any | str | None], tuple[Any, Any, Any | Literal[0], Any, Any, Any]]:
    """Repeat radial gradient."""
    ...

def draw_pattern(svg, node, pattern, font_size, opacity, stroke) -> bool:
    """Draw given gradient node."""
    ...

def apply_filters(svg, node, filter_node, font_size) -> None:
    """Apply filters defined in given filter node."""
    ...

def paint_mask(svg, node, mask, font_size) -> None:
    """Apply given mask node."""
    ...

