name: Python PR Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  verify-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.14'

      - name: Verify Python Version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Try to run app
        run: |
          cd src
          python app.py